name: AZURE TEST ACR

env:
  AZURE_RESOURCE_GROUP: 'rg-test-aks-central-us'
  AZURE_AKS_CLUSTER: 'my-free-aks'
  AZURE_ACR_NAME: 'ricardoysh'
  IMAGE_NAME: 'java-hello-world'
  IMAGE_TAG: ${{ github.sha }}


on:
 [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  test-acr:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4
    - name: Az Login & test Acr
      run: |
        az login \
          --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

        echo "------------ ACR NAME:-----------------"
        echo ${{ env.AZURE_ACR_NAME }}
        echo "---------------------------------------"
        echo " "
        echo "-------------- INFOS: ACR LIST ---------------"
        az acr list -g ${{ env.AZURE_RESOURCE_GROUP }} >> acr.json
        echo " "
        echo "------------- Subscription & RG ----------------"
        jq -r '.[].id' acr.json
        echo "---------------------------------------"
        echo "----------- ACR CreatedBy -------------"
        jq -r '.[].systemData' acr.json
        echo "---------------------------------------"
        echo " "
        echo "---------- Az ACR Login --------------"
        az acr login --name "${{ env.AZURE_ACR_NAME }}" --verbose
        echo " -------------- Finish ---------------"
        echo " "
        #echo "---------- Health Check: --------------"
        #az acr check-health --name ${{ env.AZURE_ACR_NAME }} --yes

    - name: Teste de Conectividade com o ACR ${{ env.AZURE_ACR_NAME }}
      run: |
         echo "Executando az acr check-health para  ${{ env.AZURE_ACR_NAME }}"
         az acr check-health --name ${{ env.AZURE_ACR_NAME }} --yes
         
    # - name: Testar Conectividade com ACR (az acr check-health)
    #   id: check_health
    #   uses: azure/cli@v2
    #   with:
    #     inlineScript: |
    #       echo "Executando az acr check-health para  ${{ env.AZURE_ACR_NAME }}"
    #       # O comando check-health verifica a conectividade de rede, DNS e autenticação
    #       az acr check-health --name  ${{ env.AZURE_ACR_NAME }} --yes
